### ISSUE TITLE
'<=' not supported between instances of 'tuple' and 'int'

### ISSUE THREAD

**Issue by hzlhzlhzlhzl** [Jeff-sjtu/HybrIK#104]
0% 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/demo_image.py", line 144, in <module>
    focal_length=focal, height=image.shape[0], width=image.shape[1])
  File "/content/HybrIK/hybrik/utils/render_pytorch3d.py", line 81, in render_mesh
    imgs = renderer(mesh)
  File "/usr/local/envs/hybrik/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/envs/hybrik/lib/python3.7/site-packages/pytorch3d/renderer/mesh/renderer.py", line 54, in forward
    fragments = self.rasterizer(meshes_world, **kwargs)
  File "/usr/local/envs/hybrik/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/envs/hybrik/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 151, in forward
    cull_backfaces=raster_settings.cull_backfaces,
  File "/usr/local/envs/hybrik/lib/python3.7/site-packages/pytorch3d/renderer/mesh/rasterize_meshes.py", line 115, in rasterize_meshes
    if image_size <= 64:
TypeError: '<=' not supported between instances of 'tuple' and 'int'
我在运行colab时出现的，一开始是在scipy==1.1.0时出现No module named 'scipy.spatial.transform'，我把scipy更新后出现上述bug

**Comment by timbsb** [comment]
I was also confused yesterday. now I solved this problem. It is because the version of PyTorch is too old. pip can install version 0.3.0 only. I use Conda to solve this problem like this:
```
!source activate hybrik && conda install -c pytorch3d pytorch3d -y
```
