### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by NoLookDefense** [Jeff-sjtu/HybrIK#11]
Hello. When I was training with 
**./scripts/train_smpl.sh train_res34 ./configs/256x192_adam_lr1e-3-res34_smpl_3d_base_2x_mix.yaml**
An error occurs:

Traceback (most recent call last):
  File "./scripts/train_smpl.py", line 373, in <module>
    main()
  File "./scripts/train_smpl.py", line 236, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(opt, cfg))
  File "/home/jack/anaconda3/envs/hybrik/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/home/jack/anaconda3/envs/hybrik/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/jack/anaconda3/envs/hybrik/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/media/jack/6e1ff86c-973a-4c7d-acc8-acd6f9fe7b45/research/HybrIK/scripts/train_smpl.py", line 321, in main_worker
    loss, acc17 = train(opt, train_loader, m, criterion, optimizer, writer)
  File "/media/jack/6e1ff86c-973a-4c7d-acc8-acd6f9fe7b45/research/HybrIK/scripts/train_smpl.py", line 57, in train
    output = m(inps, trans_inv, intrinsic_param, root, depth_factor, None)
  File "/home/jack/anaconda3/envs/hybrik/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jack/anaconda3/envs/hybrik/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 376, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/jack/anaconda3/envs/hybrik/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/jack/6e1ff86c-973a-4c7d-acc8-acd6f9fe7b45/research/HybrIK/hybrik/models/simple3dposeBaseSMPL.py", line 311, in forward
    return_verts=True
  File "/media/jack/6e1ff86c-973a-4c7d-acc8-acd6f9fe7b45/research/HybrIK/hybrik/models/layers/smpl/SMPL.py", line 261, in hybrik
    leaf_thetas=leaf_thetas)
  File "/media/jack/6e1ff86c-973a-4c7d-acc8-acd6f9fe7b45/research/HybrIK/hybrik/models/layers/smpl/lbs.py", line 341, in hybrik
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/media/jack/6e1ff86c-973a-4c7d-acc8-acd6f9fe7b45/research/HybrIK/hybrik/models/layers/smpl/lbs.py", line 436, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/home/jack/anaconda3/envs/hybrik/lib/python3.6/site-packages/torch/functional.py", line 211, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: size of dimension does not match previous size, operand 1, dim 2

**Comment by Jeff-sjtu** [comment]
Hi, what is your PyTorch version?

**Comment by Jeff-sjtu** [comment]
The Pytorch 1.2.0 might fix this issue.

**Comment by NoLookDefense** [comment]
Hello. I am using pytorch 1.2.0, but the problem still remains unsolved. I wonder what's your environment?

**Comment by Jeff-sjtu** [comment]
I think this error cames from the wrong version of the SMPL model, posted in #24. Did you use the v1.1.0 model?

**Comment by Jeff-sjtu** [comment]
no response, close
