### ISSUE TITLE
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Woo-ing** [Jeff-sjtu/HybrIK#153]
I have get an error when I run the nipynb in Colab : 

!source activate hybrik && python scripts/demo_image.py --img-dir examples --out-dir res

Traceback (most recent call last):
  File "scripts/demo_image.py", line 12, in <module>
    from hybrik.utils.render_pytorch3d import render_mesh
  File "/content/HybrIK/hybrik/utils/render_pytorch3d.py", line 3, in <module>
    import pytorch3d.renderer
  File "/usr/local/envs/hybrik/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 7, in <module>
    from .blending import (
  File "/usr/local/envs/hybrik/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 10, in <module>
    from pytorch3d import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
---------------------------------------------------------------------------

Can someone help me?

**Comment by alexinnovap** [comment]
This also happened to me, did you manage to fix it?

**Comment by AmoghTiwari** [comment]
This is an issue with pytorch3d installation. I had also encountered. And while I was not able to solve this directly, I tried installing things from scratch following pytorch3d's official installation instructions, and was able to solve it eventually. You can look at #186 for details.
