### ISSUE TITLE
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by alexinnovap** [Jeff-sjtu/HybrIK#174]
> (hybrik) innova@innova:~/environment/HybrIK$ python scripts/demo_image.py --img-dir examples --out-dir res
> Traceback (most recent call last):
>   File "scripts/demo_image.py", line 12, in <module>
>     from hybrik.utils.render_pytorch3d import render_mesh
>   File "/home/innova/environment/HybrIK/hybrik/utils/render_pytorch3d.py", line 3, in <module>
>     import pytorch3d.renderer
>   File "/home/innova/anaconda3/envs/hybrik/lib/python3.8/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
>     from .blending import (
>   File "/home/innova/anaconda3/envs/hybrik/lib/python3.8/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
>     from pytorch3d import _C
> ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
> 

Anyone fixed this issue?

**Comment by AmoghTiwari** [comment]
This is an issue with pytorch3d installation. I had also encountered. And while I was not able to solve this directly, I tried installing things from scratch following pytorch3d's official installation instructions, and was able to solve it eventually. You can look at #186 for details.
