### ISSUE TITLE
I encountered some error

### ISSUE THREAD

**Issue by JSWLDG** [Jeff-sjtu/HybrIK#191]
I want to train hybrik model so I comman

./scripts/train_smpl_cam.sh test_3dpw configs/256x192_adam_lr1e-3-res34_smpl_3d_cam_2x_mix_w_pw3d.yaml

then 

Traceback (most recent call last):
  File "./scripts/train_smpl_cam.py", line 361, in <module>
    main()
  File "./scripts/train_smpl_cam.py", line 208, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(opt, cfg))
  File "/home/jsw/anaconda3/envs/bybrik/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/jsw/anaconda3/envs/bybrik/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/jsw/anaconda3/envs/bybrik/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGSEGV

this error message was emerged.

I want to know what's the problem

**Comment by biansy000** [comment]
It may be the reason. You may try changing https://github.com/Jeff-sjtu/HybrIK/blob/9b8681dcf3c902dd5dacc01520ba04982990e1e2/configs/256x192_adam_lr1e-3-res34_smpl_3d_cam_2x_mix_w_pw3d.yaml#L66  to ``WORLD_SIZE: 1``
