### ISSUE TITLE
Error about mp.spawn

### ISSUE THREAD

**Issue by zengyiwen123** [Jeff-sjtu/HybrIK#198]
############# Starting Epoch 0 | LR: 0.001 #############
  0%|                                                                                                                                         | 0/4878 [00:00<?, ?it/s]Traceback (most recent call last):
  File "./scripts/train_smpl_cam.py", line 375, in <module>
    main()
  File "./scripts/train_smpl_cam.py", line 213, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(opt, cfg))
  File "/home/ubuntu/anaconda3/envs/3D/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/anaconda3/envs/3D/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/ubuntu/anaconda3/envs/3D/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 3 terminated with signal SIGKILL

**Comment by OliverSTH** [comment]
I also encountered the same problem as you, how did you solve it, thank you
