### ISSUE TITLE
fail to import .pk file using Hybrlk add-on

### ISSUE THREAD

**Issue by AWangji** [Jeff-sjtu/HybrIK#212]
hi, thanks for your great work.
But when I try importing a ".pk" file with your add-on, it fails and says: no module named torch:
![企业微信截图_1700047389392](https://github.com/Jeff-sjtu/HybrIK/assets/42883258/75014500-53f9-4c73-8bdc-50b664c2b36e)
I have no idea why cause that. Does anyone have any suggestion?

**Comment by AWangji** [comment]
The above question has been resolved. But a new strange problem appears:
![image](https://github.com/Jeff-sjtu/HybrIK/assets/42883258/14481a78-b690-4c83-a3d3-cc9649c974ca)
when I try to import pk file, it says:
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hybrik_blender_addon\__init__.py", line 69, in execute
    load_bvh(res_db, root_path, gender)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hybrik_blender_addon\convert2bvh.py", line 198, in load_bvh
    ob, obname, arm_ob = init_scene(scene, root_path, gender)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\hybrik_blender_addon\convert2bvh.py", line 68, in init_scene
    cam_ob = bpy.data.objects['Camera']
KeyError: 'bpy_prop_collection[key]: key "Camera" not found'
what should I do

**Comment by Desync-o-tron** [comment]
hi did you check this pr convo? https://github.com/Jeff-sjtu/HybrIK/pull/170
