### ISSUE TITLE
Errors while running Google Collab

### ISSUE THREAD

**Issue by OphisOuro** [Jeff-sjtu/HybrIK#220]
**When running the Google Collab cells, I get errors regarding PyTorch3D. Is there any known way to fix this?** 

`Building wheels for collected packages: pytorch3d
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pytorch3d (setup.py) ... error
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects`

**Probably in relation to this, the "run video" cell ends with this error:**

`Traceback (most recent call last):
  File "scripts/demo_video.py", line 14, in <module>
    from hybrik.models import builder
  File "/content/HybrIK/hybrik/models/__init__.py", line 7, in <module>
    from .HRNetSMPLXCamKid import HRNetSMPLXCamKid
  File "/content/HybrIK/hybrik/models/HRNetSMPLXCamKid.py", line 6, in <module>
    from hybrik.models.layers.smplx.body_models import SMPLXLayer
  File "/content/HybrIK/hybrik/models/layers/smplx/body_models.py", line 29, in <module>
    from .lbs import (
  File "/content/HybrIK/hybrik/models/layers/smplx/lbs.py", line 25, in <module>
    from pytorch3d.transforms.rotation_conversions import (axis_angle_to_matrix,
ModuleNotFoundError: No module named 'pytorch3d'`

**Comment by OtakuOW** [comment]
<img width="1013" alt="Senza titolo" src="https://github.com/Jeff-sjtu/HybrIK/assets/138236457/12cb4ad0-5d18-42c1-b487-ced9920a6b19">

**Comment by OtakuOW** [comment]
other: ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.

tf-keras 2.15.1 requires tensorflow<2.16,>=2.15, but you have tensorflow 2.16.1 which is incompatible.

torchaudio 2.2.1+cu121 requires torch==2.2.1, but you have torch 2.1.0 which is incompatible.

torchtext 0.17.1 requires torch==2.2.1, but you have torch 2.1.0 which is incompatible.

**Comment by OtakuOW** [comment]
help me
