### ISSUE TITLE
validation code stuck in loading models

### ISSUE THREAD

**Issue by seoha-kim** [Jeff-sjtu/HybrIK#25]
i set all datasets and run validation scripts
but it stuck in loading models like below:

tcp://127.0.0.1:23456, ws:4, rank:1
Loading model from ./pretrained_res34.pth...
tcp://127.0.0.1:23456, ws:4, rank:0
Loading model from ./pretrained_res34.pth...

is there anything else i should do?
i set all the pretrained weights and smpl files

**Comment by Jeff-sjtu** [comment]
Hi @seoha-kim ,

It seems you run the code in a two-GPU machine. You can set the `WORLD_SIZE` to `2` in the config file before you run validate.

**Comment by seoha-kim** [comment]
``Traceback (most recent call last):
  File "./scripts/validate_smpl.py", line 250, in <module>
    main()
  File "./scripts/validate_smpl.py", line 201, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(opt, cfg))
  File "/home/ubuntu/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ubuntu/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ubuntu/seoha/HybrIK/scripts/validate_smpl.py", line 226, in main_worker
    train=False)
  File "/home/ubuntu/seoha/HybrIK/hybrik/datasets/hp3d.py", line 148, in __init__
    self._items, self._labels = self._lazy_load_json()
  File "/home/ubuntu/seoha/HybrIK/hybrik/datasets/hp3d.py", line 175, in _lazy_load_json
    items, labels = self._load_jsons()
  File "/home/ubuntu/seoha/HybrIK/hybrik/datasets/hp3d.py", line 191, in _load_jsons
    database = json.load(fid)
  File "/home/ubuntu/anaconda3/envs/hybrik/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/ubuntu/anaconda3/envs/hybrik/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/envs/hybrik/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/anaconda3/envs/hybrik/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 393200 (char 393199)``

oh.. after modifying that this error occurs..

**Comment by Jeff-sjtu** [comment]
It seems that the error occurs during loading the JSON annotation files of 3DHP. Is the file path correct?

**Comment by seoha-kim** [comment]
Oh, I asked a stupid question.
It's all settled now. Thanks.

**Comment by Jeff-sjtu** [comment]
I'm glad everything's worked out ;)

**Comment by nanfengguli** [comment]
> Oh, I asked a stupid question. It's all settled now. Thanks.

So, may I ask how you did it? I have the same problem. Loading files is slow. It feels like it’s stuck.
