### ISSUE TITLE
error in validate

### ISSUE THREAD

**Issue by KamiCalcium** [Jeff-sjtu/HybrIK#38]
Hi,

I face this error when validating:

-- Process 3 terminated with the following error:

Traceback (most recent call last):

  File "/dump/algopre/c-szan/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap

    fn(i, *args)

  File "/dump/algopre/c-szan/github/HybrIK/scripts/validate_smpl.py", line 239, in main_worker

    gt_tot_err = validate_gt(m, opt, cfg, gt_val_dataset_hp3d, heatmap_to_coord, opt.batch)

  File "/dump/algopre/c-szan/github/HybrIK/scripts/validate_smpl.py", line 169, in validate_gt

    with open(os.path.join('exp', f'test_gt_kpt_rank_{opt.rank}.pkl'), 'wb') as fid:

FileNotFoundError: [Errno 2] No such file or directory: 'exp/test_gt_kpt_rank_3.pkl'

What is this exp directory? Am I supposed to first train it? But I only want to use the pre-trained model to do the validate. Any idea?

Thanks!

**Comment by Jeff-sjtu** [comment]
Hi @KamiCalcium, I think you can solve this problem by creating an empty folder `exp` in the root directory.
