### ISSUE TITLE
Inference bugs with trained model

### ISSUE THREAD

**Issue by rshaojimmy** [Jeff-sjtu/HybrIK#39]
Hi, when I carry out inference with trained models, such as best_h36m_model.pth and best_3dpw_model.pth, the following error will be reported using the ./configs/256x192_adam_lr1e-3-res34_smpl_24_3d_base_2x_mix.yaml as suggested:

RuntimeError: Error(s) in loading state_dict for Simple3DPoseBaseSMPL24:
        Missing key(s) in state_dict: "decleaf.weight", "decleaf.bias". 
        size mismatch for final_layer.weight: copying a param with shape torch.Size([1856, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([1536, 256, 1, 1]).
        size mismatch for final_layer.bias: copying a param with shape torch.Size([1856]) from checkpoint, the shape in current model is torch.Size([1536]).
        size mismatch for smpl.children_map: copying a param with shape torch.Size([29]) from checkpoint, the shape in current model is torch.Size([24]).
        size mismatch for smpl.parents: copying a param with shape torch.Size([29]) from checkpoint, the shape in current model is torch.Size([24]).

So I switch to the configs file used in the training as: ./configs/256x192_adam_lr1e-3-res34_smpl_3d_base_2x_mix.yaml, still the following error is reported:

Traceback (most recent call last):
  File "/mnt/lustre/shaorui/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "xxx/hybrik/scripts/validate_smpl.py", line 251, in main_worker
    gt_tot_err = validate_gt(m, opt, cfg, gt_val_dataset_3dpw, heatmap_to_coord, opt.batch, test_vertice=True)
  File "xxx/hybrik/scripts/validate_smpl.py", line 102, in validate_gt
    gt_output = m.module.forward_gt_theta(gt_thetas, gt_betas)
  File "xxx/hybrik/hybrik/models/simple3dposeBaseSMPL.py", line 346, in forward_gt_theta
    return_verts=True
  File "xxx/hybrik/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "xxx/hybrik/hybrik/models/layers/smpl/SMPL.py", line 207, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "xxx/hybrik/hybrik/models/layers/smpl/lbs.py", line 269, in lbs
    J_transformed, A = batch_rigid_transform(rot_mats, J, parents, dtype=dtype)
  File "xxx/hybrik/hybrik/models/layers/smpl/lbs.py", line 512, in batch_rigid_transform
    rel_joints[:, 1:] -= joints[:, parents[1:]].clone()
RuntimeError: The size of tensor a (23) must match the size of tensor b (28) at non-singleton dimension 1

Seems there exist some issues about the dimension when inference and may I ask how to fix them.

Thanks so much.

**Comment by rshaojimmy** [comment]
I have checked the code once again. 

In the training, we use the configs file 256x192_adam_lr1e-3-res34_smpl_3d_base_2x_mix.yaml which uses Simple3DPoseBaseSMPL as the training model. 

However, README tells us to the use 256x192_adam_lr1e-3-res34_smpl_24_3d_base_2x_mix.yaml to do the validation/inference. In this configs file,  Simple3DPoseBaseSMPL24 is the inference model which has extra self.decleaf = nn.Linear(1024, 5 * 4) layer that does not exist in the Simple3DPoseBaseSMPL used in the training. So how can we load the training checkpoint with the Simple3DPoseBaseSMPL24? 

And if I use the same Simple3DPoseBaseSMPL to do validation, the error of RuntimeError: The size of tensor a (23) must match the size of tensor b (28) at non-singleton dimension 1 appears.

So may I ask how fix this bug? thanks.

**Comment by Jeff-sjtu** [comment]
Hi @rshaojimmy, during testing, you should use the config file that is also used for training. Is there still bugs when using the same config file?

**Comment by rshaojimmy** [comment]
Yes. 

Using the same config file, still the following bug is reported when tested with 3dpw after setting test_vertice=True in the validate_smpl.py:

Traceback (most recent call last):
File "/mnt/lustre/shaorui/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
fn(i, *args)
File "xxx/hybrik/scripts/validate_smpl.py", line 251, in main_worker
gt_tot_err = validate_gt(m, opt, cfg, gt_val_dataset_3dpw, heatmap_to_coord, opt.batch, test_vertice=True)
File "xxx/hybrik/scripts/validate_smpl.py", line 102, in validate_gt
gt_output = m.module.forward_gt_theta(gt_thetas, gt_betas)
File "xxx/hybrik/hybrik/models/simple3dposeBaseSMPL.py", line 346, in forward_gt_theta
return_verts=True
File "xxx/hybrik/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in call
result = self.forward(*input, **kwargs)
File "xxx/hybrik/hybrik/models/layers/smpl/SMPL.py", line 207, in forward
self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
File "xxx/hybrik/hybrik/models/layers/smpl/lbs.py", line 269, in lbs
J_transformed, A = batch_rigid_transform(rot_mats, J, parents, dtype=dtype)
File "xxx/hybrik/hybrik/models/layers/smpl/lbs.py", line 512, in batch_rigid_transform
rel_joints[:, 1:] -= joints[:, parents[1:]].clone()
RuntimeError: The size of tensor a (23) must match the size of tensor b (28) at non-singleton dimension 1

Seems there exist some issues about the dimension when tested with 3dpw data.
