### ISSUE TITLE
RuntimeError: NCCL error 

### ISSUE THREAD

**Issue by rawalkhirodkar** [Jeff-sjtu/HybrIK#47]
Thank you for the great work.

I am having issues evaluating the pretrained model, ./validate_smpl.sh

The script validate_smpl.sh looks like
```
cd ..

CONFIG=./configs/256x192_adam_lr1e-3-res34_smpl_24_3d_base_2x_mix.yaml
CKPT=./models/pretrained_res34.pth
PORT=${3:-23456}

HOST=$(hostname -i)

NCCL_DEBUG=INFO python ./scripts/validate_smpl.py \
    --batch 32 \
    --gpus 0,1,2,3 \
    --world-size 4 \
    --flip-test \
    --launcher pytorch --rank 0 \
    --dist-url tcp://${HOST}:${PORT} \
    --cfg ${CONFIG} \
    --checkpoint ${CKPT}

```

The error log:
```
ued37c44e4ea65b:6861:6861 [7] init.cc:981 NCCL WARN Invalid rank requested : 7/4
ued37c44e4ea65b:6859:6859 [5] init.cc:981 NCCL WARN Invalid rank requested : 5/4
ued37c44e4ea65b:6860:6860 [6] NCCL INFO Bootstrap : Using [0]enp1s0f0:10.49.66.196<0>
ued37c44e4ea65b:6860:6860 [6] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
ued37c44e4ea65b:6860:6860 [6] NCCL INFO NET/IB : No device found.
ued37c44e4ea65b:6860:6860 [6] NCCL INFO NET/Socket : Using [0]enp1s0f0:10.49.66.196<0>

ued37c44e4ea65b:6860:6860 [6] init.cc:981 NCCL WARN Invalid rank requested : 6/4
ued37c44e4ea65b:6854:7877 [0] NCCL INFO Setting affinity for GPU 0 to 03,fffff000,003fffff
ued37c44e4ea65b:6856:7878 [2] NCCL INFO Setting affinity for GPU 2 to 03,fffff000,003fffff
ued37c44e4ea65b:6857:7879 [3] NCCL INFO Setting affinity for GPU 3 to 03,fffff000,003fffff
ued37c44e4ea65b:6855:6855 [1] NCCL INFO Bootstrap : Using [0]enp1s0f0:10.49.66.196<0>
ued37c44e4ea65b:6855:6855 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
ued37c44e4ea65b:6855:6855 [1] NCCL INFO NET/IB : No device found.
ued37c44e4ea65b:6855:6855 [1] NCCL INFO NET/Socket : Using [0]enp1s0f0:10.49.66.196<0>
ued37c44e4ea65b:6855:7880 [1] NCCL INFO Setting affinity for GPU 1 to 03,fffff000,003fffff
Traceback (most recent call last):
  File "./scripts/validate_smpl.py", line 250, in <module>
    main()
  File "./scripts/validate_smpl.py", line 201, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(opt, cfg))
  File "/home/ANT.AMAZON.COM/khirawal/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ANT.AMAZON.COM/khirawal/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/home/ANT.AMAZON.COM/khirawal/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ANT.AMAZON.COM/khirawal/Desktop/ochmr/hybrik/scripts/validate_smpl.py", line 219, in main_worker
    m = torch.nn.parallel.DistributedDataParallel(m, device_ids=[opt.gpu])
  File "/home/ANT.AMAZON.COM/khirawal/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 298, in __init__
    self.broadcast_bucket_size)
  File "/home/ANT.AMAZON.COM/khirawal/anaconda3/envs/hybrik/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 480, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /tmp/pip-req-build-58y_cjjl/torch/lib/c10d/../c10d/NCCLUtils.hpp:39, invalid argument
```

Any suggestions? Thank you.

**Comment by rawalkhirodkar** [comment]
Update: Resolved, I had 8 gpus on the server, used CUDA_VISIBLE_DEVICES=0,1,2,3, to hide 4.
